// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS6BW7yR0sZUYE-pof5C-vcbTnpKClhuk',
    appId: '1:137787904263:web:e2c5555273ef1a24d635a2',
    messagingSenderId: '137787904263',
    projectId: 'roomschatapp-22ed8',
    authDomain: 'roomschatapp-22ed8.firebaseapp.com',
    storageBucket: 'roomschatapp-22ed8.appspot.com',
    measurementId: 'G-7SVPZLW4JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZEv7pLIZztvJPc-_AELBQMNEzFIKGWr8',
    appId: '1:137787904263:android:3ed73338fe3e563ad635a2',
    messagingSenderId: '137787904263',
    projectId: 'roomschatapp-22ed8',
    storageBucket: 'roomschatapp-22ed8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjbOT4P2YXErskU3hNbKiwFEcydPaSDOo',
    appId: '1:137787904263:ios:7599f14ea683bec3d635a2',
    messagingSenderId: '137787904263',
    projectId: 'roomschatapp-22ed8',
    storageBucket: 'roomschatapp-22ed8.appspot.com',
    iosClientId: '137787904263-a1mka0c2cdufar86sl6h2cuol763jske.apps.googleusercontent.com',
    iosBundleId: 'com.IBMF.roomsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjbOT4P2YXErskU3hNbKiwFEcydPaSDOo',
    appId: '1:137787904263:ios:a7ab93c626974af4d635a2',
    messagingSenderId: '137787904263',
    projectId: 'roomschatapp-22ed8',
    storageBucket: 'roomschatapp-22ed8.appspot.com',
    iosClientId: '137787904263-8lj0t59medt71jcam7pdvf314e90thql.apps.googleusercontent.com',
    iosBundleId: 'com.IBMF.roomsChat.RunnerTests',
  );
}
